### PR TITLE
Makefile, admesh as dependency

### PR DESCRIPTION
**Pull request by jmlich**
This pull request consist of following changes:

The admesh package is available in Fedora. From my point of view, it seems to be better to use upstream version of admesh rather than bundling of own version.

The build is done using Makefile. Additionally, It have clean and install target. The opencv libraries are cflags and libs is from pkg-config.

Readme was renamed to README.md and updated have markdown syntax (i.e. it looks pretty on github web page)

This was proposed in #9

### CODE REVIEW

**Comment by kliment** [comment]
Can you update the readme to state that admesh is no longer included in the file and to reflect the new makefile?

**Comment by jmlich** [comment]
Previously, there was ~~striketrough~~ in markdown. The comit 3fba877decd66f355b8c4890396adf9554f64fe0 removes that string.

**Comment by kliment** [comment]
No, I meant that the build instructions don't currently mention the admesh package and still refer to build.sh

**Comment by jmlich** [comment]
Oh I see. It is better now?

**Comment by kliment** [comment]
Yes, except I would change "the Makefile script" to "make"

**Pull request merged**
